base_config_path: /experiments/base/discriminator.yaml
batch_growth_increment: 0.1
dataset:
  filter_protons: false
  max_dataset_length: 10000000
  regression_target: crystal_reduced_volume
device: cuda
early_epochs_step_override: 5
extra_test_period: 1
grow_batch_size: true
history: 100
logger:
  experiment_tag: crystal_analyser
  log_figures: true
  run_name: crystal_analyzer
  sample_reporting_frequency: 10
machine: local
max_batch_size: 5000
max_epochs: 10000
min_batch_size: 500
minimum_epochs: 500
num_early_epochs: 0
overfit_tolerance: 4
