# WORK IN PROGRESS
[tool.poetry]
name = "mxtaltools"
version = "0.1.0"
description = "MXtalTools: Molecular Crystals Machine Learning Toolkit"
authors = ["Michael Kilgour <mjakilgour@gmail.com>"]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: BSD-3",
    "Operating System :: Windows, Linux",
]

[tool.poetry.urls]
repository = "https://github.com/InfluenceFunctional/MXtalTools"
issues = "https://github.com/InfluenceFunctional/MXtalTools/issues"
# documentation = 

keywords = ["molecular crystal", "molecular material", "graph neural network"]

[tool.poetry.dependencies]
python = "^3.7"
dependencies = [
  "numpy",
  "scipy",
  "scikit-learn",
  "torch>=2.0.1",
  "pyg",
  "torch_scatter",
  "torch_cluster",
  "torch_sparse",
  "wandb",
  "tqdm",
  "ase",
  "pytest",
  "numba",
  "plotly",
  "kaleido",
]

exclude = [
  "old",
]
