test_mode: False
machine: "cluster"
device: "cuda"
explicit_run_enumeration: True
skip_saving_and_loading: True
run_num: 10164
anomaly_detection: False
mode: gan  # 'gan' or 'regression' or 'figures' or 'sampling' or 'autoencoder'
save_checkpoints: True # will do it always on cluster, only locally if True

# for GAN training
freeze_generator_conditioner: False
train_generator_packing: True
train_generator_vdw: True
vdw_loss_rescaling: null
packing_loss_rescaling: null
train_generator_combo: False
train_generator_h_bond: False # (non-directional)
train_generator_adversarially: False
generator_similarity_penalty: 0

train_discriminator_adversarially: False
train_discriminator_on_randn: False
train_discriminator_on_distorted: True
sample_distortion_magnitude: 0.0001 # -1 for wide range test # noise for distorted generation

extra_test_period: 10
extra_test_evaluation: False
extra_test_set_paths: null
discriminator_path: '/home/mk8347/scratch/csd_runs/models/best_discriminator_10088'
generator_path: null #'C:/Users\mikem\crystals\CSP_runs\models/cluster/best_generator_10135'
conditioner_path: null
regressor_path: null

sample_steps: 10
sample_move_size: 0.001

seeds:
  model: 0
  dataset: 0

# opt - sweep details
wandb:
  mini_csp_frequency: 10
  sample_reporting_frequency: 5
  experiment_tag: generator8
  log_figures: True

# batching & convergence
accumulate_gradients: False # DEPRECATED
accumulate_batch_size: 100 # DEPRECATED
auto_batch_sizing: False # DEPRECATED
auto_batch_reduction: 0.05 # DEPRECATED # fraction of tested max batch size to actually start with (unequal graph sizes)
grow_batch_size: True
min_batch_size: 10
max_batch_size: 10000
batch_growth_increment: 0.01 # fraction of batch size to grow by each epoch
max_epochs: 10000 # 0 epochs takes us straight to evaluation mode
history: 5000
gradient_norm_clip: 1

# dataset curation
target: packing # 'density' or 'packing' or 'volume'
dataset_length: 10000000
feature_richness: full # full or minimal
max_crystal_temperature: 10000
min_crystal_temperature: -100
max_num_atoms: 100
min_num_atoms: 5 # target XVI has only 9 heavy atoms
max_molecule_radius: 10 # angstroms
max_z_value: 18
min_z_value: 0
max_z_prime: 1
min_z_prime: 1
max_packing_coefficient: 0.85
min_packing_coefficient: 0.55
include_organic: True
include_organometallic: True
max_atomic_number: 20
exclude_missing_r_factor: False
exclude_disordered_crystals: True
exclude_polymorphs: True
exclude_nonstandard_settings: True #False
exclude_crystal_systems: null #['hexagonal','trigonal','rhombohedral']
exclude_blind_test_targets: False
include_sgs: null #[ "P-1","P21/c","P212121","C2/c" ] #["P-1", "P21/c", "P212121", "C2/c", "Pbca", "P21"]
include_pgs: null # DEPRECATED [222,-1,2/m] #[222, -1, 2/m, 2, mm2, mmm, m]
generate_sgs: null #["P-1","P21/c","P212121","C2/c"] #'P2' #'P21/c' # can only do one at a time right now
supercell_size: 5 # new method - should be very large, automatically pares down


# discriminator optimizer and model
discrimiator_optimizer:
  optimizer: adam
  init_lr: 1.0E-6
  max_lr: 2.0E-5
  min_lr: 5.0E-6
  lr_schedule: True
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001
  training_period: 10
  lr_growth_lambda: 1.05
  lr_shrink_lambda: 0.99

discriminator:
  positional_noise: 0 # scaling for the randn noise added to all atom positions
  crystal_convolution_type: 2 # 1 - counts inter and intramolecular the same, 2 - separates intermolecular
  graph_convolution_layers: 4
  graph_filters: 36
  atom_embedding_size: 128
  graph_norm: graph
  num_spherical: 5
  num_radial: 32
  graph_convolution_cutoff: 6 # vdw direct force approx 6 angstrom
  max_num_neighbors: 100
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 4 # mikenet GATv2 mode only - must evenly divide graph filters
  graph_convolution: 'TransformerConv' # 'full message passing' or schnet or 'GATv2'
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False #
  pooling: combo

  num_fc_layers: 4
  fc_depth: 256
  activation: gelu
  fc_dropout_probability: 0
  fc_norm_mode: layer

#generator optimizer and model
generator_optimizer:
  optimizer: adamw
  init_lr: 1.0E-4
  max_lr: 1.0E-3
  min_lr: 1.0E-4
  lr_schedule: True
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  weight_decay: 0.01
  convergence_eps: 0.00001
  lr_growth_lambda: 1.05
  lr_shrink_lambda: 0.99

generator:
  canonical_conformer_orientation: 'random' # 'standardized' 'random'
  positional_noise: 0 # scaling for the randn noise added to all atom positions
  num_fc_layers: 4
  fc_depth: 256
  activation: 'gelu'
  fc_dropout_probability: 0
  fc_norm_mode: null

  prior: multivariate normal
  prior_dimension: 12

# conditioner optimizer and model
conditioner_optimizer:
  optimizer: adamw
  init_lr: 5.0E-4
  max_lr: 1.0E-3
  min_lr: 1.0E-4
  lr_schedule: True
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  weight_decay: 0.01
  convergence_eps: 0.00001
  lr_growth_lambda: 1.01
  lr_shrink_lambda: 0.99

conditioner:
  init_decoder_size: 1
  init_atom_embedding_dim: 5
  positional_noise: 0 # scaling for the randn noise added to all atom positions
  graph_convolution_layers: 4
  graph_filters: 128
  atom_embedding_size: 256
  output_dim: 256
  graph_norm: null
  num_spherical: 6
  num_radial: 32
  graph_convolution_cutoff: 1
  max_num_neighbors: 100
  radial_function: 'gaussian' #
  num_attention_heads: 4 # mikenet GATv2 mode only - must evenly divide graph filters
  graph_convolution: 'TransformerConv' #'TransformerConv' 'none' GATv2, schnet, or full message passing, or 'TransformerConv'
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False
  pooling: max # combo, geometric max mean sum attention
  positional_embedding: 'sph3' # 'sph' or 'pos' or 'combo', for 'geometric' pooling

  num_fc_layers: 4
  fc_depth: 1024
  activation: 'gelu'
  fc_dropout_probability: 0.5
  fc_norm_mode: null

  decoder_embedding_dim: 2048
  decoder_resolution: 0.5 # angstrom
  decoder_classes: 'full' # 'minimal' or 'full'

regressor_optimizer:
  optimizer: adamw
  init_lr: 1.0E-4
  max_lr: 1.0E-3
  min_lr: 1.0E-4
  lr_schedule: True
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  weight_decay: 0.01
  convergence_eps: 0.00001
  lr_growth_lambda: 1.05
  lr_shrink_lambda: 0.975

regressor:
  positional_noise: 0 # scaling for the randn noise added to all atom positions
  graph_convolution_layers: 2
  graph_filters: 64
  atom_embedding_size: 512
  graph_norm: null
  num_spherical: 6
  num_radial: 50
  graph_convolution_cutoff: 3
  max_num_neighbors: 100
  radial_function: 'gaussian' # mikenet only
  num_attention_heads: 4 # mikenet GATv2 mode only - must evenly divide graph filters
  graph_convolution: 'TransformerConv' #'TransformerConv' 'none' GATv2, schnet, or full message passing, or 'TransformerConv'
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False
  pooling: max # combo, geometric max mean sum attention
  positional_embedding: 'sph3' # 'sph' or 'pos' or 'combo', for 'geometric' pooling

  num_fc_layers: 2
  fc_depth: 1024
  activation: 'gelu'
  fc_dropout_probability: 0.5
  fc_norm_mode: null