#First, define the dataset by a series of conditions in format [key, type, [elements]]
#where type is in not_in or range and elements are [min, max], or a list of discrete values
#
#Then, specify the features which will be fed to models in training

seed: 1
max_dataset_length: 1000000
save_dataset: False

regression_target: 'molecule_dipole_moment' # 'crystal_reduced_cell_volume' 'crystal_density' 'crystal_packing_coefficient'
single_molecule_dataset_identifier: null
test_fraction: 0.2

filter_polymorphs: False
filter_duplicate_molecules: False
filter_conditions: null

atom_feature_keys: [
'atom_atomic_numbers'
]

molecule_feature_keys : [
'molecule_num_atoms'
]
