test_mode: False
machine: "cluster"
device: "cuda"
skip_run_init: False
explicit_run_enumeration: True
skip_saving_and_loading: True
run_num: 992
anomaly_detection: False
mode: gan # 'gan' or 'regression' or 'figures'
gan_loss: standard #wasserstein # standard #distance
new_generation: True # new way of defining asymmetric unit
train_generator_density: False
train_generator_packing: True
train_generator_vdw: True
train_generator_adversarially: False
train_discriminator_adversarially: False
train_discriminator_on_randn: False
train_discriminator_on_noise: False
generator_noise_level: 0.1 # -1 for wide range test # noise for distorted generation
generator_similarity_penalty: 0
extra_test_period: 1
sample_after_training: False
sample_ind: 0
sample_steps: 10
sample_move_size: 0.05
extra_test_set_paths: null #[ 'C:/Users/mikem/Desktop/CSP_runs/datasets/blind_test_5_dataset',
                        #'C:/Users/mikem/Desktop/CSP_runs/datasets/blind_test_6_dataset',
                        #'C:/Users/mikem/Desktop/CSP_runs/datasets/blind_test_targets',]
                        #'C:/Users/mikem/Desktop/CSP_runs/datasets/bt_31_dataset',
                        #'C:/Users/mikem/Desktop/CSP_runs/datasets/bt_31_targets',]
d_model_path: null #'C:\Users\mikem\Desktop\CSP_runs\models/cluster/discriminator_931'
g_model_path: null #'C:\Users\mikem\Desktop\CSP_runs\models/cluster/generator_951'

seeds:
  model: 0
  dataset: 0

# opt - sweep details
wandb:
  sample_reporting_frequency: 1
  experiment_tag: dev
  log_figures: True

# batching & convergence
auto_batch_sizing: True
min_batch_size: 2
max_batch_size: 100
auto_batch_reduction: .6 # fraction of tested max batch size to actually start with (unequal graph sizes)
max_epochs: 10000 # 0 epochs takes us straight to evaluation mode
history: 5000
gradient_norm_clip: 1

# dataset curation
target: packing # 'density' or 'packing' or 'volume'
dataset_length: 10000
feature_richness: full # full or minimal
max_crystal_temperature: 1000
min_crystal_temperature: -100
max_num_atoms: 40
min_num_atoms: 8 # target XVI has only 9 heavy atoms
max_z_value: 18
min_z_value: 0
max_z_prime: 1
min_z_prime: 1
max_packing_coefficient: 0.85
min_packing_coefficient: 0.55
include_organic: True
include_organometallic: False
max_atomic_number: 20
exclude_missing_r_factor: False
exclude_disordered_crystals: True
exclude_polymorphs: True
exclude_nonstandard_settings: True #False
exclude_crystal_systems: null #['hexagonal','trigonal','rhombohedral']
exclude_blind_test_targets: True
include_sgs: ["P-1"] #["P-1", "P21/c", "P212121", "C2/c", "Pbca", "P21"]
include_pgs: null #[222,-1,2/m] #[222, -1, 2/m, 2, mm2, mmm, m]
generate_sgs: null #'P2' #'P21/c' # can only do one at a time right now
supercell_size: 5 # new method - should be very large, automatically pares down

# https://www.ruppweb.org/Xray/tutorial/enantio.htm non enantiogenic groups

# discriminator optimizer and model
discriminator:
  optimizer: "adamw"
  learning_rate: 0.00001
  max_lr: 0.00001
  lr_schedule: False
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001
  training_period: 1
  positional_noise: 0 # scaling for the randn noise added to all atom positions

  crystal_convolution_type: 2 # 1 - counts inter and intramolecular the same, 2 - separates intermolecular
  graph_convolution_layers: 4
  graph_filters: 128
  atom_embedding_size: 256
  graph_norm: layer
  num_spherical: 6
  num_radial: 32
  graph_convolution_cutoff: 6 # vdw direct force approx 6 angstrom
  max_num_neighbors: 100
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 1 # mikenet self attention mode only - must evenly divide graph filters
  graph_convolution: 'full message passing' # 'full message passing' or schnet or 'self attention'
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False #
  pooling: combo

  num_fc_layers: 4
  fc_depth: 256
  activation: leaky relu
  fc_dropout_probability: 0.1
  fc_norm_mode: layer

# generator optimizer and model
generator:
  optimizer: adamw
  learning_rate: 0.00001
  max_lr: 0.0001
  lr_schedule: True
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  weight_decay: 0.01
  convergence_eps: 0.00001
  positional_noise: 0 # scaling for the randn noise added to all atom positions

  model_type: mlp # mlp only
  graph_convolution_layers: 5
  graph_filters: 128
  atom_embedding_size: 512
  graph_norm: layer
  num_spherical: 6
  num_radial: 12
  graph_convolution_cutoff: 3
  max_num_neighbors: 100
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 4 # mikenet self attention mode only - must evenly divide graph filters
  graph_convolution: 'self attention' # self attention, schnet, or full message passing
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False
  pooling: combo

  conditioner_num_fc_layers: 4
  conditioner_fc_depth: 512
  conditioner_activation: leaky relu
  conditioner_fc_dropout_probability: 0.1
  conditioner_fc_norm_mode: layer

  num_fc_layers: 40
  fc_depth: 512
  activation: leaky relu
  fc_dropout_probability: 0.1
  fc_norm_mode: layer

  num_samples: 1000
  prior: multivariate normal
  conditional_modelling: True # false will likely not run at all
  conditioning_mode: graph model # molecule features or graph model
