test_mode: True
machine: "local"
device: "cuda"
skip_run_init: False
explicit_run_enumeration: False
skip_saving_and_loading: True
run_num: 0
anomaly_detection: False
mode: cell gan # 'single molecule regression' 'single molecule classification' 'joint modelling' 'cell classification' 'cell gan'
gan_loss: wasserstein #wasserstein # standard
train_generator_density: False
train_generator_as_flow: False
train_generator_on_randn: False
train_generator_adversarially: True
train_generator_range_cutoff: True
train_generator_packing: True
train_discriminator_adversarially: True
train_discriminator_on_randn: False # todo finish
train_discriminator_on_noise: False # todo finish
cut_flow_training_after: 5

seeds:
  model: 0
  dataset: 0

# opt - sweep details
wandb:
  sweep_config_file: "sweep_test.yaml"
  experiment_tag: "new_clean_data_testing"
  log_figures: True
  sample_reporting_frequency: 1
  sweep: False
  sweep_id: null
  sweep_num_runs: 50

# dataset curation
target: crystal spacegroup setting # not currently used
positional_noise: 0 # scaling for the randn noise added to all atom positions
dataset_length: 10000
max_crystal_temperature: 1000
min_crystal_temperature: -100
max_num_atoms: 40
min_num_atoms: 20
max_z_value: 10
min_z_value: 0
max_z_prime: 1
min_z_prime: 1
max_packing_coefficient: 0.85
min_packing_coefficient: 0.58
include_organic: True
include_organometallic: True
max_atomic_number: 87
exclude_missing_r_factor: False
exclude_disordered_crystals: True
exclude_polymorphs: True
exclude_nonstandard_settings: True
include_sgs: null #[P-1, P21/c, P212121, C2/c, Pbca, P21]
include_pgs: ['2/m'] #[222,-1,2/m] #[222, -1, 2/m, 2, mm2, mmm, m]
generate_pgs: '2/m' #'1'
supercell_size: 3 # 1 = 3x3x3, 2 = 5x5x5 etc.

# batching & convergence
auto_batch_sizing: True
min_batch_size: 10
max_batch_size: 2000
auto_batch_reduction: .65
max_epochs: 1000
history: 200

# discriminator optimizer and model
discriminator:
  optimizer: "adamw"
  learning_rate: 0.00001
  max_lr: 0.001
  lr_schedule: True
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001

  graph_model: mike
  graph_convolution_layers: 1
  graph_filters: 16
  atom_embedding_size: 16
  graph_norm: layer
  num_spherical: 6
  num_radial: 12
  graph_convolution_cutoff: 5
  max_num_neighbors: 32
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 1 # mikenet only
  graph_convolution: 'full message passing' # mikenet only
  add_spherical_basis: False # mikenet only
  pooling: attention

  num_fc_layers: 1
  fc_depth: 16
  activation: leaky relu
  fc_dropout_probability: 0.1
  fc_norm_mode: layer

# generator optimizer and model
generator:
  optimizer: "adamw"
  learning_rate: 0.000001
  max_lr: 0.0001
  lr_schedule: True
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001

  model_type: mlp # mlp or nf
  graph_model: mike
  graph_convolution_layers: 4
  graph_filters: 32
  atom_embedding_size: 64
  graph_norm: layer
  num_spherical: 6
  num_radial: 12
  graph_convolution_cutoff: 5
  max_num_neighbors: 32
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 1 # mikenet only
  graph_convolution: 'full message passing' # mikenet only
  add_spherical_basis: False # mikenet only
  pooling: attention

  num_fc_layers: 4
  fc_depth: 128
  activation: leaky relu
  fc_dropout_probability: 0.1
  fc_norm_mode: layer

  num_samples: 1000
  prior: multivariate normal
  conditional_modelling: True # false will likely not run at all
  conditioning_mode: graph model # molecule features or graph model

  num_flow_layers: 12
  flow_depth: 128
  flow_basis_fns: 8
  flow_type: nsf_cl

