test_mode: False
machine: "local"
device: "cuda"
skip_run_init: False
explicit_run_enumeration: False
skip_saving_and_loading: True
run_num: 0
mode: cell gan # 'single molecule regression' 'single molecule classification' 'joint modelling' 'cell classification' 'cell gan'
gan_loss: standard
train_generator_density: True
train_generator_as_flow: False
train_generator_adversarially: False
train_discriminator_adversarially: False

seeds:
  model: 0
  dataset: 0

# opt - sweep details
wandb:
  sweep_config_file: "sweep_test.yaml"
  experiment_tag: "new_clean_data_testing"
  log_figures: True
  sample_reporting_frequency: 2
  sweep: False
  sweep_id: null
  sweep_num_runs: 50

# dataset curation
target: crystal spacegroup setting
length: 10000
max_crystal_temperature: 1000
min_crystal_temperature: -100
max_num_atoms: 60
min_num_atoms: 20
max_z_value: 10
min_z_value: 0
max_z_prime: 1
min_z_prime: 1
max_packing_coefficient: 0.85
min_packing_coefficient: 0.58
include_organic: True
include_organometallic: True
max_atomic_number: 87
exclude_missing_r_factor: False
exclude_disordered_crystals: True
exclude_polymorphs: False
exclude_nonstandard_settings: True
include_sgs: null #[P-1, P21/c, P212121, C2/c, Pbca, P21]
include_pgs: null #[222, -1, 2/m, 2, mm2, mmm, m, 1, 422]

# batching & convergence
auto_batch_sizing: False
initial_batch_size: 100
auto_batch_reduction: 0.2
max_epochs: 500
history: 100

# discriminator optimizer and model
discriminator:
  optimizer: "adamw"
  learning_rate: 0.001
  max_lr: 0.001
  lr_schedule: False
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001

  graph_model: mike
  graph_convolution_layers: 2
  graph_filters: 16
  atom_embedding_size: 16
  graph_norm: null
  num_spherical: 6
  num_radial: 12
  graph_convolution_cutoff: 5
  max_num_neighbors: 10
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 1 # mikenet only
  graph_convolution: 'full message passing' # mikenet only
  add_spherical_basis: False # mikenet only
  pooling: attention

  num_fc_layers: 1
  fc_depth: 16
  activation: "gelu"
  fc_dropout_probability: 0
  fc_norm_mode: null

# generator optimizer and model
generator:
  optimizer: "adamw"
  learning_rate: 0.001
  max_lr: 0.001
  lr_schedule: False
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001

  model_type: mlp # or nf
  graph_model: mike
  graph_convolution_layers: 8
  graph_filters: 16
  atom_embedding_size: 32
  graph_norm: layer
  num_spherical: 6
  num_radial: 12
  graph_convolution_cutoff: 5
  max_num_neighbors: 10
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 1 # mikenet only
  graph_convolution: 'full message passing' # mikenet only
  add_spherical_basis: False # mikenet only
  pooling: attention

  num_fc_layers: 4
  fc_depth: 64
  activation: "gelu"
  fc_dropout_probability: 0.1
  fc_norm_mode: layer

  num_samples: 10000
  prior: multivariate normal
  conditional_modelling: True # false will likely not run at all
  conditioning_mode: graph model # molecule features or graph model

  num_flow_layers: 4
  flow_depth: 32
  flow_basis_fns: 8
  flow_type: nsf_cl

