machine: "local"  # or "cluster"
device: "cuda"  # or "cpu"
base_config_path: /experiments/base/autoencoder.yaml

dataset:
  max_dataset_length: 100
  filter_protons: True

# batching & convergence
grow_batch_size: True
min_batch_size: 10
max_batch_size: 10000
minimum_epochs: 2
max_epochs: 2 # 0 epochs takes us straight to sampling/evaluation (only implemented for GAN)

logger:
  sample_reporting_frequency: 1  # how often to do detailed reporting with figures
  run_name: autoencoder_test
  experiment_tag: test