machine: "local"  # or "cluster"
device: "cpu"  # or "cpu"
anomaly_detection: False  # slows down the code
mode: regression  # 'gan' or 'regression' or 'figures' or 'embedding' or 'sampling' WIP
dataset_name: 'test_dataset.pkl'
dataset_yaml_path: 'C:/Users/mikem/OneDrive/NYU/CSD/MCryGAN/configs/dataset/full_regression_for_tests.yaml'
save_checkpoints: False # will do it always on cluster, only locally if True

dataset:
  max_dataset_length: 100

# batching & convergence
grow_batch_size: False
min_batch_size: 100
max_batch_size: 100
batch_growth_increment: 0.05 # fraction of batch size to grow by each epoch
max_epochs: 1 # 0 epochs takes us straight to sampling/evaluation (only implemented for GAN)
history: 5000  # for convergence checks
gradient_norm_clip: 1

logger:
  run_name: test
  mini_csp_frequency: 5
  sample_reporting_frequency: 1
  log_figures: True
  experiment_tag: test

sample_steps: 20 # now for mini csp
sample_move_size: 0.001 # currently unused

extra_test_set_path: null # not currently working
extra_test_period: 5 # how often to evaluate on extra test sets (hardcoded analysis per extra test set)

seeds:
  model: 0
  dataset: 0

# for reloading prior checkpoints
discriminator_path: null #'C:\Users\mikem\crystals\CSP_runs\models\cluster\best_discriminator_10413'
generator_path: null #'C:\Users\mikem\crystals\CSP_runs\models\cluster\best_generator_10440'
regressor_path: null  # 'C:\Users\mikem\crystals\CSP_runs\models\cluster\best_regressor_431'

discriminator_positional_noise: 0
generator_positional_noise: 0
regressor_positional_noise: 0

generate_sgs: 'all'  #'["P21/c"] #["P-1","P21/c","P212121","C2/c"] # null -> will generate in original sg.  'all' -> will randomly pick between all possibilities. []
supercell_size: 5
# for GAN training
generator:
  canonical_conformer_orientation: 'random' # 'standardized' 'random'
  packing_target_noise: 0.05 # randn noise magnitude in the standardized basis
  train_vdw: True
  train_adversarially: True
  vdw_loss_func: inv  # null 'mse' or 'log' or 'inv'
  density_loss_func: l1  # 'l1' or 'mse'
  adversarial_loss_func: 'score'  #
  train_h_bond: True # (non-directional)
  similarity_penalty: 0.1

  #generator optimizer and model
  optimizer:
    optimizer: adamw
    init_lr: 5.0E-4
    max_lr: 1.0E-3
    min_lr: 1.0E-4
    lr_schedule: True
    beta1: 0.9 #0.9
    beta2: 0.999 #0.999
    weight_decay: 0.01
    convergence_eps: 0.00001
    lr_growth_lambda: 1.05
    lr_shrink_lambda: 0.99

  model:
    num_fc_layers: 4
    fc_depth: 512
    activation: 'gelu'
    fc_dropout_probability: 0.5
    fc_norm_mode: layer
    conditioning_mode: 'first_layer' # 'first_layer' only for now

    prior: multivariate normal
    prior_dimension: 12  # NOTE this must be 12
    radial_norm_factor: 5

    conditioner:
      graph_convolution_type: TransformerConv
      graph_aggregator: combo
      concat_mol_to_atom_features: False
      activation: gelu
      num_fc_layers: 4
      fc_depth: 512
      fc_norm_mode: layer
      fc_dropout_probability: 0.5
      graph_node_norm: 'graph layer'
      graph_node_dropout: 0.5
      graph_message_norm: null
      graph_message_dropout: 0.2
      num_attention_heads: 4
      graph_message_depth: 64
      graph_node_dims: 512
      num_graph_convolutions: 2
      graph_embedding_depth: 512
      nodewise_fc_layers: 2
      num_radial: 50
      radial_function: gaussian
      max_num_neighbors: 100
      convolution_cutoff: 6
      atom_type_embedding_dims: 5

discriminator:
  train_adversarially: True
  train_on_randn: True
  train_on_distorted: True
  distortion_magnitude: 0.1 # -1 for wide range test # noise for distorted generation

  # discriminator optimizer and model
  optimizer:
    optimizer: adamw
    init_lr: 1.0E-4
    max_lr: 2.0E-4
    min_lr: 1.0E-4
    lr_schedule: True
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.001
    convergence_eps: 0.00001
    training_period: 1
    lr_growth_lambda: 1.05
    lr_shrink_lambda: 0.99

  model:
    graph_convolution_type: TransformerConv
    graph_aggregator:  combo
    concat_mol_to_atom_features: True
    activation: gelu
    num_fc_layers: 2
    fc_depth: 128
    fc_norm_mode: 'layer'
    fc_dropout_probability: 0.5
    graph_node_norm: 'graph layer'
    graph_node_dropout: 0.5
    graph_message_norm: null
    graph_message_dropout: 0.5
    num_attention_heads: 4
    graph_message_depth: 128
    graph_node_dims: 256
    num_graph_convolutions: 4
    graph_embedding_depth: 256
    nodewise_fc_layers: 1
    num_radial: 12
    radial_function: bessel
    max_num_neighbors: 100
    convolution_cutoff: 6
    atom_type_embedding_dims: 5
    periodic_convolution_type: 'all_layers'  # or 'last_layer'

regressor:
  optimizer:
    optimizer: adamw
    init_lr: 1.0E-4
    max_lr: 1.0E-3
    min_lr: 1.0E-4
    lr_schedule: True
    beta1: 0.9 #0.9
    beta2: 0.999 #0.999
    weight_decay: 0.01
    convergence_eps: 0.00001
    lr_growth_lambda: 1.05
    lr_shrink_lambda: 0.975

  model:
    graph_convolution_type: TransformerConv
    graph_aggregator :  combo
    concat_mol_to_atom_features: True
    activation: gelu
    num_fc_layers: 4
    fc_depth: 128
    fc_norm_mode: 'layer'
    fc_dropout_probability: 0.1
    graph_node_norm: 'graph layer'
    graph_node_dropout: 0.1
    graph_message_norm: null
    graph_message_dropout: 0.1
    num_attention_heads: 4
    graph_message_depth: 128
    graph_node_dims: 256
    num_graph_convolutions: 4
    graph_embedding_depth: 256
    nodewise_fc_layers: 1
    num_radial: 12
    radial_function: bessel
    max_num_neighbors: 100
    convolution_cutoff: 6
    atom_type_embedding_dims: 5
