test_mode: True
machine: "local"  # or "cluster"
device: "cpu"
explicit_run_enumeration: False
skip_saving_and_loading: True
run_num: 0
anomaly_detection: True
mode: regression  # 'gan' or 'regression' or 'figures' or 'sampling' WIP
save_checkpoints: False # will do it always on cluster, only locally if True

# for GAN training
packing_target_noise: 0.05 # randn noise magnitude in the standardized basis
train_generator_vdw: True
train_generator_adversarially: True
vdw_loss_rescaling: null
train_generator_h_bond: True # (non-directional)
generator_similarity_penalty: 1

train_discriminator_adversarially: True
train_discriminator_on_randn: True
train_discriminator_on_distorted: True
sample_distortion_magnitude: -1 # -1 for wide range test # noise for distorted generation

extra_test_period: 100
extra_test_evaluation: False
extra_test_set_paths: null
discriminator_path: null
generator_path: null
regressor_path: null

discriminator_positional_noise: 0.1  # scaling for the randn noise added to all atom positions
generator_positional_noise: 0.1  # scaling for the randn noise added to all atom positions
regressor_positional_noise: 0.1  # scaling for the randn noise added to all atom positions

seeds:
  model: 0
  dataset: 0

# opt - sweep details
wandb:
  mini_csp_frequency: 10
  sample_reporting_frequency: 5
  experiment_tag: GAN_test
  log_figures: True

sample_steps: 10 # now for mini csp

# batching & convergence
grow_batch_size: True
min_batch_size: 10
max_batch_size: 10000
batch_growth_increment: 0.05 # fraction of batch size to grow by each epoch
max_epochs: 2 # 0 epochs takes us straight to evaluation (only implemented for GAN)
history: 1
gradient_norm_clip: 1

# dataset curation
target: packing # 'density' or 'packing' or 'volume'
dataset_length: 100
feature_richness: full # full or minimal
max_crystal_temperature: 1000 # set very high to include full dataset
min_crystal_temperature: -100 # set below -1 to include all entries with missing temps
max_num_atoms: 100
min_num_atoms: 5 # target XVI has only 9 heavy atoms
max_molecule_radius: 100 # angstroms
max_z_value: 18
min_z_value: 0
max_z_prime: 1
min_z_prime: 1
max_packing_coefficient: 0.85
min_packing_coefficient: 0.55
include_organic: True
include_organometallic: True
max_atomic_number: 100
exclude_missing_r_factor: False
exclude_disordered_crystals: True
exclude_polymorphs: False
exclude_nonstandard_settings: True #False
exclude_crystal_systems: null #['hexagonal','trigonal','rhombohedral']
exclude_blind_test_targets: True
include_sgs: null  # ["P-1","P21/c","P212121","C2/c"]  # null for all
generate_sgs: ["P-1","P21/c","P212121","C2/c"] # null -> will generate in original sg.  'all' -> will randomly pick between all possibilities
supercell_size: 5 # new method - should be very large, automatically pares down

# discriminator optimizer and model
discriminator_optimizer:
  optimizer: adamw
  init_lr: 1.0E-5
  max_lr: 1.0E-4
  min_lr: 1.0E-5
  lr_schedule: True
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001
  training_period: 1
  lr_growth_lambda: 1.05
  lr_shrink_lambda: 0.99

discriminator:
  crystal_convolution_type: 2 # 1 - counts inter and intramolecular the same, 2 - separates intermolecular
  graph_convolution_layers: 2
  graph_filters: 32
  atom_embedding_size: 32
  graph_norm: 'graph layer' # layer, graph, batch, graph layer
  num_spherical: 5
  num_radial: 32
  graph_convolution_cutoff: 6 # vdw direct force approx 6 angstrom
  max_num_neighbors: 100
  radial_function: 'bessel' # 'gaussian' or 'bessel'
  num_attention_heads: 4 # mikenet GATv2 or TransformerConv mode only - must evenly divide graph filters
  graph_convolution: 'TransformerConv' # 'full message passing' or schnet or 'GATv2' or 'TransformerConv'
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False #
  pooling: combo

  num_fc_layers: 2
  fc_depth: 32
  activation: gelu
  fc_dropout_probability: 0
  fc_norm_mode: layer # batch, layer

#generator optimizer and model
generator_optimizer:
  optimizer: adamw
  init_lr: 1.0E-4
  max_lr: 5.0E-4
  min_lr: 1.0E-4
  lr_schedule: True
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  weight_decay: 0.01
  convergence_eps: 0.00001
  lr_growth_lambda: 1.05
  lr_shrink_lambda: 0.99

generator:
  canonical_conformer_orientation: 'random' # 'standardized' 'random'
  num_fc_layers: 2
  fc_depth: 32
  activation: 'gelu'
  fc_dropout_probability: 0
  fc_norm_mode: layer

  prior: multivariate normal
  prior_dimension: 12

  conditioner:
    skinny_atomwise_features: False  # cut atom features down to bare minimum for conditioner input
    concat_mol_features: True  # exclusive with skinny features
    init_atom_embedding_dim: 5
    graph_convolution_layers: 1
    graph_filters: 32
    atom_embedding_size: 32
    output_dim: 32
    graph_norm: 'graph layer'
    num_spherical: 6
    num_radial: 32
    graph_convolution_cutoff: 3
    max_num_neighbors: 100
    radial_function: 'gaussian' # bessel or gaussian
    num_attention_heads: 4 # mikenet GATv2 mode only - must evenly divide graph filters
    graph_convolution: 'TransformerConv' #'TransformerConv' 'none' GATv2, schnet, or full message passing, or 'TransformerConv'
    add_spherical_basis: False # mikenet only
    add_torsional_basis: False
    pooling: max # combo, geometric max mean sum attention
    positional_embedding: 'sph3' # 'sph' or 'pos' or 'combo', for 'geometric' pooling  # todo deprecate

    num_fc_layers: 0
    fc_depth: 32
    activation: 'gelu'
    fc_dropout_probability: 0
    fc_norm_mode: layer

regressor_optimizer:
  optimizer: adamw
  init_lr: 1.0E-4
  max_lr: 1.0E-3
  min_lr: 1.0E-5
  lr_schedule: True
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  weight_decay: 0.01
  convergence_eps: 0.00001
  lr_growth_lambda: 1.05
  lr_shrink_lambda: 0.975

regressor:
  graph_convolution_layers: 2
  graph_filters: 32
  atom_embedding_size: 32
  graph_norm: 'graph layer'
  num_spherical: 6
  num_radial: 32
  graph_convolution_cutoff: 3
  max_num_neighbors: 100
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 4 # mikenet GATv2 mode only - must evenly divide graph filters
  graph_convolution: 'TransformerConv' #'TransformerConv' 'none' GATv2, schnet, or full message passing, or 'TransformerConv'
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False
  pooling: combo # combo, geometric max mean sum attention
  positional_embedding: 'sph3' # 'sph' or 'pos' or 'combo', for 'geometric' pooling

  num_fc_layers: 2
  fc_depth: 32
  activation: 'gelu'
  fc_dropout_probability: 0
  fc_norm_mode: layer